Repository mattermost/mattermost-plugin-calls, pull requests merged in 2022-10, with the labels that each got.

#213 [MM-46993] Global widget desktop communication
  Makefile
  webapp/src/components/call_widget/component.scss
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/screen_source_modal/component.tsx
  webapp/src/index.tsx
  webapp/src/utils.ts
  widget/src/index.tsx
  widget/webpack.config.js
Labels: 3: Reviews Complete

#209 [MM-47159] Add linux-arm64 target to release build
  Makefile
Labels: 3: Reviews Complete

#191 [MM-47001] Fix accessibility conflict
  e2e/tests/shortcuts.spec.ts
  webapp/src/components/call_widget/component.tsx
Labels: 1: UX Review

#215 Make consistent order of hands up
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/reaction_stream/reaction_stream.tsx
Labels: 3: Reviews Complete

#217 [MM-47364] Disable crash on hovering disabled button
  webapp/src/components/call_widget/widget_button.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/controls_button.tsx
  webapp/src/components/shared.tsx
Labels: 3: Reviews Complete

#219 [MM-47395] Avoid fetching resources if user is not logged in
  webapp/src/index.tsx
Labels: 3: Reviews Complete

#223 Fix participant screen overflow
  webapp/src/components/expanded_view/component.tsx
Labels: 3: Reviews Complete

#192 MM-47046 Use version of React DOM provided by web app
  webapp/package-lock.json
  webapp/package.json
  webapp/webpack.config.js
Labels: 3: Reviews Complete

#228 [MM-47827] Fix mute toggle shortcut tooltip in expanded view
  webapp/src/components/expanded_view/component.tsx
Labels: 3: Reviews Complete

#225 [MM-47659] Properly fix element stacking
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-participants-list-boards-chromium-linux.png
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-participants-list-boards-webkit-linux.png
  webapp/src/components/call_widget/component.tsx
Labels: 3: Reviews Complete

#229 Fix e2e tests
  webapp/package-lock.json
Labels: 2: Dev Review, 2: QA Review

#231 [MM-47933] Improve logging and tracking of resources
  webapp/src/client.ts
  webapp/src/components/call_widget/component.tsx
Labels: 3: Reviews Complete
