Repository mattermost/mattermost-plugin-calls, pull requests merged in 2022-07, with the labels that each got.

#135 [MM-42138] Avoid duplicate profiles in the redux state
  webapp/src/reducers.ts
Labels: 3: Reviews Complete

#137 [MM-45499] Fix ordering to avoid race condition on session initialization
  server/websocket.go
Labels: 3: Reviews Complete

#108 [MM-44486] Support advanced ICE server configs through ICEServersConfigs
  build/manifest/main.go
  go.mod
  go.sum
  plugin.json
  server/activate.go
  server/configuration.go
  webapp/src/client.ts
  webapp/src/selectors.ts
  webapp/src/types/types.ts
Labels: 3: Reviews Complete, Docs Needed

#116 [MM-45001] Add support for generating short-lived TURN credentials
  plugin.json
  server/activate.go
  server/api.go
  server/configuration.go
  server/main.go
  server/plugin.go
  webapp/src/index.tsx
  webapp/src/selectors.ts
  webapp/src/types/types.ts
Labels: 1: Editor Review, Docs Needed

#141 Fixed invalid json format
  plugin.json
Labels: 3: Reviews Complete

#143 e2e: Gitlab integration
  .gitlab-ci.yml
  e2e/global-setup.ts
  e2e/playwright.config.ts
Labels: 3: Reviews Complete

#145 [MM-43838] WebSocket reconnection support
  go.mod
  go.sum
  server/activate.go
  server/client_message.go
  server/cluster_message.go
  server/configuration.go
  server/main.go
  server/plugin.go
  server/session.go
  server/websocket.go
  webapp/src/client.ts
  webapp/src/websocket.ts
Labels: 3: Reviews Complete

#147 [MM-45288] Return empty array instead of null
  server/api.go
Labels: 3: Reviews Complete

#148 e2e: Gitlab -> Github status reporting
  e2e/playwright.config.ts
Labels: 3: Reviews Complete
