Repository mattermost/mattermost-plugin-calls, pull requests merged in 2022-12, with the labels that each got.

#250 [MM-48219] Recordings: outstanding UI changes
  e2e/package-lock.json
  e2e/package.json
  e2e/tests/shortcuts.spec.ts
  e2e/tests/start_call.spec.ts
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-bottom-bar-chromium-linux.png
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-bottom-bar-dm-chromium-linux.png
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-bottom-bar-dm-webkit-linux.png
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-bottom-bar-webkit-linux.png
  e2e/tests/start_call.spec.ts-snapshots/dm-calls-widget-bottom-bar-chromium-linux.png
  e2e/tests/start_call.spec.ts-snapshots/dm-calls-widget-bottom-bar-webkit-linux.png
  standalone/src/recording/components/recording_view/component.tsx
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/widget_banner.tsx
  webapp/src/components/expanded_view/component.scss
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/controls_button.tsx
  webapp/src/components/expanded_view/in_call_prompt.tsx
  webapp/src/components/expanded_view/reaction_button.tsx
  webapp/src/components/icons/muted_icon.tsx
  webapp/src/components/icons/raised_hand.tsx
  webapp/src/components/icons/unraised_hand.tsx
  webapp/src/shortcuts.ts
  webapp/src/types/telemetry.ts
Labels: 2: Dev Review

#254 [MM-48746] Implement basic error surfacing
  server/channel_state.go
  server/recording_api.go
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/in_call_prompt.tsx
  webapp/src/types/types.ts
  webapp/src/utils.ts
Labels: 1: Editor Review

#249 [MM-48668] Recording state improvements
  go.mod
  go.sum
  server/activate.go
  server/channel_state.go
  server/recording_api.go
  server/session.go
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/in_call_prompt.tsx
  webapp/src/types/types.ts
  webapp/src/utils.ts
Labels: 3: Reviews Complete

#255 Fix integrity checks
  Makefile
  standalone/package-lock.json
  standalone/skip_integrity_check.js
Labels: 3: Reviews Complete

#262 Fix potential edge case
  server/session.go
Labels: 3: Reviews Complete

#263 Fix e2e tests on MacOS
  e2e/global-setup.ts
  e2e/package-lock.json
  e2e/tests/join_call.spec.ts-snapshots/channel-toast-chromium-darwin.png
  e2e/tests/shortcuts.spec.ts
  e2e/tests/start_call.spec.ts
  e2e/tests/start_call.spec.ts-snapshots/calls-screen-source-modal-chromium-darwin.png
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-bottom-bar-chromium-darwin.png
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-bottom-bar-dm-chromium-darwin.png
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-participants-list-boards-chromium-darwin.png
Labels: 2: Dev Review

#267 [MM-48898] Implement info prompt for approaching max call duration
  plugin.json
  server/configuration.go
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/index.ts
  webapp/src/components/expanded_view/recording_info_prompt.tsx
  webapp/src/selectors.ts
  webapp/src/types/types.ts
Labels: 1: Editor Review

#268 MM-48719 - Fix reaction stream rendering while screensharing
  webapp/src/components/expanded_view/component.tsx
Labels: 3: Reviews Complete

#259 MM-48720 - Calls GA requirements
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-participants-list-boards-chromium-darwin.png
  plugin.json
  server/activate.go
  server/api.go
  server/channel_state.go
  server/cloud_limits.go
  server/configuration.go
  server/configuration_test.go
  server/plugin.go
  server/session.go
  server/utils.go
  server/utils_test.go
  server/websocket.go
  webapp/i18n/en.json
  webapp/src/actions.ts
  webapp/src/components/admin_console_settings/test_mode/index.tsx
  webapp/src/components/channel_header_button/component.tsx
  webapp/src/components/channel_header_button/index.ts
  webapp/src/components/channel_header_dropdown_button/component.tsx
  webapp/src/components/channel_header_dropdown_button/index.ts
  webapp/src/components/channel_header_menu_button/index.ts
  webapp/src/components/modals/index.tsx
  webapp/src/index.tsx
  webapp/src/reducers.ts
  webapp/src/selectors.ts
  webapp/src/types/mattermost-webapp/index.d.ts
  webapp/src/types/types.ts
  webapp/src/utils.ts
Labels: 3: Reviews Complete

#270 [MM-48928] Outstanding UX for recordings
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/index.ts
  webapp/src/components/call_widget/widget_banner.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/controls_button.tsx
  webapp/src/components/expanded_view/in_call_prompt.tsx
  webapp/src/components/expanded_view/index.ts
  webapp/src/components/expanded_view/recording_info_prompt.tsx
  webapp/src/reducers.ts
  webapp/src/selectors.ts
Labels: 3: Reviews Complete

#271 Fix missing ws events
  server/session.go
  server/websocket.go
Labels: 3: Reviews Complete

#273 Fix trailing slash in services URLs
  server/job_service.go
  server/rtcd.go
Labels: 3: Reviews Complete

#269 MM-48859 - Fix for: Emoji picker doesn't open after opened once
  standalone/package-lock.json
  standalone/package.json
  standalone/src/widget.tsx
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/end_call_modal/component.tsx
  webapp/src/components/expanded_view/reaction_button.tsx
Labels: 3: Reviews Complete

#261 [MM-48853] Update README
  README.md
Labels: 3: Reviews Complete

#44 load-test client
  README.md
  go.mod
  lt/README.md
  lt/client.go
  lt/samples/audio.ogg
  lt/samples/video.ivf
  lt/ws/client.go
  lt/ws/client_test.go
Labels: 3: Reviews Complete

#274 MM-49020 - Fix nil deref
  server/configuration.go
Labels: 3: Reviews Complete

#278 MM-47358 - Fix: Cancelling screen sharing results in "system preferences" client side error
  webapp/src/constants.ts
Labels: 3: Reviews Complete

#277 MM-48657 - Add close button to pop-out window on desktop
  e2e/tests/popout.spec.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/expanded_view/component.tsx
Labels: 3: Reviews Complete

#279 [MM-49078] Disable joining sound after threshold
  webapp/src/websocket_handlers.ts
Labels: 3: Reviews Complete

#281 MM-48076 MM-49085: Global expanded view fixes
  webapp/src/components/expanded_view/component.tsx
Labels: 3: Reviews Complete

#280 [MM-49086] Implement authentication check and re-registration logic in case of failure
  server/job_service.go
Labels: 3: Reviews Complete

#276 [MM-46048] Implement glare-free negotiation
  webapp/src/components/call_widget/component.tsx
  webapp/src/rtcpeer/index.ts
Labels: 3: Reviews Complete
