Repository mattermost/mattermost-plugin-calls, pull requests merged in 2022-11, with the labels that each got.

#233 [MM-48041] Add support for building standalone clients
  .circleci/config.yml
  Makefile
  e2e/tests/global_widget.spec.ts
  server/api.go
  standalone/.eslintrc.json
  standalone/.gitignore
  standalone/.npmrc
  standalone/babel.config.js
  standalone/package-lock.json
  standalone/package.json
  standalone/src/common.ts
  standalone/src/init.ts
  standalone/src/theme_utils.ts
  standalone/src/types/calls.ts
  standalone/src/widget.html
  standalone/src/widget.tsx
  standalone/tsconfig.json
  standalone/webpack.config.js
  webapp/src/client.ts
  webapp/src/types/types.ts
  webapp/src/websocket.ts
Labels: 3: Reviews Complete

#234 Bump `rtcd` dependency to v0.7.0
  go.mod
  go.sum
  webapp/src/rtc_stats.ts
Labels: 3: Reviews Complete

#235 [MM-48142] Fix remaining call state issues on parent window
  webapp/src/action_types.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/custom_post_types/post_type/component.tsx
  webapp/src/index.tsx
  webapp/src/reducers.ts
Labels: 3: Reviews Complete

#236 Track total screen sharing duration per call
  server/channel_state.go
  server/session.go
  server/utils.go
  server/websocket.go
Labels: 3: Reviews Complete

#176 Call Thread in Expanded View
  e2e/tests/popout.spec.ts
  e2e/tests/popout.spec.ts-snapshots/expanded-view-controls-chromium-darwin.png
  e2e/tests/popout.spec.ts-snapshots/expanded-view-participants-grid-chromium-darwin.png
  webapp/package-lock.json
  webapp/package.json
  webapp/src/actions.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/index.ts
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/index.ts
  webapp/src/css_utils.tsx
  webapp/src/selectors.ts
  webapp/src/types/types.ts
  webapp/src/webapp_globals.ts
  webapp/webpack.config.js
Labels: 3: Reviews Complete

#218 [MM-46532] Implement AllowScreenSharing config setting
  plugin.json
  server/configuration.go
  server/websocket.go
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/index.ts
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/index.ts
  webapp/src/selectors.ts
  webapp/src/types/types.ts
Labels: 3: Reviews Complete

#241 Fix e2e snapshots
  e2e/tests/join_call.spec.ts-snapshots/channel-toast-chromium-linux.png
  e2e/tests/join_call.spec.ts-snapshots/channel-toast-webkit-linux.png
Labels: 3: Reviews Complete

#238 [MM-48074] Implement standalone recording client
  plugin.json
  server/activate.go
  server/api.go
  server/bot_api.go
  server/channel_state.go
  server/configuration.go
  server/enterprise/license.go
  server/plugin.go
  server/rtcd.go
  server/session.go
  server/websocket.go
  standalone/src/init.ts
  standalone/src/recording/action_types.ts
  standalone/src/recording/components/recording_view/component.tsx
  standalone/src/recording/components/recording_view/index.ts
  standalone/src/recording/index.html
  standalone/src/recording/index.tsx
  standalone/src/recording/reducers.ts
  standalone/src/recording/selectors.ts
  standalone/src/widget.tsx
  standalone/src/widget/index.html
  standalone/src/widget/index.tsx
  standalone/webpack.config.js
  webapp/src/selectors.ts
  webapp/src/websocket_handlers.ts
Labels: 3: Reviews Complete

#243 [MM-48351] Fix screen stream flakyness
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/expanded_view/component.tsx
Labels: 3: Reviews Complete

#244 MM-48435 - Desktop: Widget 'move' crosshairs moves the whole desktop app
  webapp/src/components/call_widget/component.tsx
Labels: 3: Reviews Complete

#247 [MM-48220] Job service
  .golangci.yml
  go.mod
  go.sum
  plugin.json
  server/activate.go
  server/api.go
  server/channel_state.go
  server/configuration.go
  server/job_api.go
  server/job_service.go
  server/plugin.go
  server/recording_api.go
  server/session.go
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/index.ts
  webapp/src/selectors.ts
  webapp/src/types/types.ts
Labels: 3: Reviews Complete

#246 [MM-48544] Implement uploads API for recordings
  .circleci/config.yml
  .golangci.yml
  go.mod
  go.sum
  plugin.json
  server/activate.go
  server/api.go
  server/audit.go
  server/bot_api.go
  server/channel_state.go
  server/configuration.go
  server/job_api.go
  server/job_service.go
  server/log.go
  server/plugin.go
  server/recording_api.go
  server/session.go
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/index.ts
  webapp/src/selectors.ts
  webapp/src/types/types.ts
Labels: 3: Reviews Complete

#237 Replacing screenshare controls with media-chrome
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/icons/compassIcon.tsx
Labels: 1: UX Review, 2: Dev Review

#240 MM-48285 - Emoji reactions in webapp
  e2e/tests/popout.spec.ts
  server/client_message.go
  server/websocket.go
  webapp/.eslintrc.json
  webapp/index.d.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/action_types.ts
  webapp/src/client.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/index.ts
  webapp/src/components/channel_link_label/index.ts
  webapp/src/components/custom_post_types/post_type/index.ts
  webapp/src/components/emoji/emoji.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/controls_button.tsx
  webapp/src/components/expanded_view/index.ts
  webapp/src/components/expanded_view/reaction_button.tsx
  webapp/src/components/icons/smiley_icon.tsx
  webapp/src/components/reaction_stream/reaction_stream.tsx
  webapp/src/constants.ts
  webapp/src/emojis/emoji.json
  webapp/src/emojis/emoji.ts
  webapp/src/index.tsx
  webapp/src/reducers.ts
  webapp/src/selectors.ts
  webapp/src/shortcuts.ts
  webapp/src/types/types.ts
  webapp/src/utils.ts
  webapp/src/websocket_handlers.ts
Labels: 1: UX Review

#252 Small fix
  server/recording_api.go
Labels: 3: Reviews Complete
