Repository mattermost/mattermost-plugin-calls, pull requests merged in 2022-09, with the labels that each got.

#178 Fix `/call stats` payload
  webapp/src/index.tsx
Labels: 3: Reviews Complete

#179 Catch connection failed
  webapp/src/rtcpeer/index.ts
Labels: 3: Reviews Complete

#171 [MM-46412] Disable calls in archived channels
  server/websocket.go
  webapp/src/components/channel_header_button/component.tsx
  webapp/src/components/channel_header_button/index.ts
  webapp/src/components/channel_header_dropdown_button/component.tsx
  webapp/src/components/channel_header_dropdown_button/index.ts
Labels: 3: Reviews Complete

#168 [MM-45025] Keyboard shortcuts
  e2e/global-setup.ts
  e2e/tests/popout.spec.ts
  e2e/tests/popout.spec.ts-snapshots/expanded-view-controls-chromium-linux.png
  e2e/tests/popout.spec.ts-snapshots/expanded-view-controls-webkit-linux.png
  e2e/tests/shortcuts.spec.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/expanded_view/component.scss
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/shortcut.tsx
  webapp/src/index.tsx
  webapp/src/shortcuts.ts
Labels: 3: Reviews Complete

#181 Use base64 payload
  server/slash_command.go
  webapp/src/index.tsx
Labels: 3: Reviews Complete

#184 [MM-46905] Fix mute/unmute shortcut in expanded view
  webapp/src/components/expanded_view/component.tsx
  webapp/src/shortcuts.ts
Labels: 3: Reviews Complete

#186 [MM-46918] Fallback to using telemetry ID as rtcd's client ID
  server/rtcd.go
Labels: 3: Reviews Complete

#180 MM-45509 - Disable and implement upgrade flow on RTCD Service URL config option
  Makefile
  build/manifest/main.go
  plugin.json
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/actions.ts
  webapp/src/cloud_pricing/modals.tsx
  webapp/src/components/admin_console_settings/rtcd_service_url/index.tsx
  webapp/src/components/admin_console_settings/rtcd_service_url/modals.tsx
  webapp/src/components/channel_header_menu_button/component.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/shared.tsx
  webapp/src/index.tsx
  webapp/src/selectors.ts
  webapp/src/types/external/styled-components.d.ts
  webapp/src/types/mattermost-webapp/index.d.ts
  webapp/src/types/types.ts
  webapp/webpack.config.js
Labels: 1: PM Review, 1: UX Review, 2: Dev Review, 1: Editor Review

#185 [MM-46807] Implement client-side telemetry
  server/api.go
  server/telemetry.go
  webapp/.eslintrc.json
  webapp/src/actions.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/index.ts
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/index.ts
  webapp/src/types/telemetry.ts
Labels: 1: UX Review

#188 MM-46947 - Fix: Manifest parsing won't allow placeholders for custom pluginSettingType
  plugin.json
Labels: 3: Reviews Complete

#198 Reaction websocket broadcast
  server/client_message.go
  server/websocket.go
Labels: 2: Dev Review

#199 Add emoji picker to calls expanded view
  webapp/index.d.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/client.ts
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/icons/smiley_icon.tsx
  webapp/src/shortcuts.ts
  webapp/src/types/types.ts
Labels: 2: Dev Review

#202 Close on click outside
  webapp/src/components/expanded_view/component.tsx
Labels: 2: Dev Review

#205 Minor bug fixes
  webapp/src/components/expanded_view/component.tsx
Labels: 3: Reviews Complete

#204 Add a timeout for reactions
  webapp/src/action_types.ts
  webapp/src/index.tsx
  webapp/src/reducers.ts
Labels: 2: Dev Review

#210 Fix bug that made all reactions in the stream disappear
  webapp/src/reducers.ts
Labels: 2: Dev Review

#212 Fix horizontal shift when adding reactions
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/reaction_stream/reaction_stream.tsx
Labels: 3: Reviews Complete

#187 [MM-46927] Implement blocking client-side errors
  webapp/src/action_types.ts
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/call_error_modal.tsx
  webapp/src/components/generic_modal.tsx
  webapp/src/components/icons/laptop_alert_svg.tsx
  webapp/src/index.tsx
  webapp/src/reducers.ts
  webapp/src/selectors.ts
Labels: 1: Editor Review

#189 [MM-46672] Implement non-blocking client errors
  e2e/tests/popout.spec.ts-snapshots/expanded-view-controls-chromium-linux.png
  e2e/tests/popout.spec.ts-snapshots/expanded-view-controls-webkit-linux.png
  e2e/tests/popout.spec.ts-snapshots/expanded-view-participants-grid-chromium-linux.png
  e2e/tests/popout.spec.ts-snapshots/expanded-view-participants-grid-webkit-linux.png
  webapp/src/client.ts
  webapp/src/components/call_widget/component.scss
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/unavailable_icon_wrapper.tsx
  webapp/src/components/call_widget/widget_banner.tsx
  webapp/src/components/call_widget/widget_button.tsx
  webapp/src/components/expanded_view/component.scss
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/controls_button.tsx
  webapp/src/components/expanded_view/global_banner.tsx
  webapp/src/components/icons/muted_icon.tsx
  webapp/src/components/icons/show_more.tsx
  webapp/src/components/icons/unmuted_icon.tsx
  webapp/src/constants.ts
  webapp/src/types/types.ts
Labels: 3: Reviews Complete
