Repository mattermost/mattermost-plugin-calls, pull requests merged in 2023-07, with the labels that each got.

#465 [MM-53508] Fix potentially empty profiles in expanded view
  webapp/src/actions.ts
Labels: 3: Reviews Complete

#461 MM-53261 - Expanded view notifications
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/incoming_calls/call_incoming_condensed.tsx
  webapp/src/components/incoming_calls/expanded_call_container.tsx
  webapp/src/components/incoming_calls/hooks.ts
  webapp/src/components/switch_call_modal/component.tsx
  webapp/src/components/switch_call_modal/index.ts
  webapp/src/utils.ts
Labels: 1: UX Review

#466 Bump deps
  go.mod
  go.sum
  plugin.json
Labels: 3: Reviews Complete

#455 MM-53322 - Channel toast fixes
  e2e/tests/channel_toast.spec.ts
  standalone/i18n/es.json
  standalone/i18n/hr.json
  standalone/i18n/it.json
  standalone/i18n/ja.json
  standalone/i18n/ko.json
  standalone/i18n/uz.json
  standalone/i18n/zh_Hans.json
  webapp/i18n/cs.json
  webapp/i18n/de.json
  webapp/i18n/es.json
  webapp/i18n/fr.json
  webapp/i18n/hr.json
  webapp/i18n/it.json
  webapp/i18n/ja.json
  webapp/i18n/ko.json
  webapp/i18n/lt.json
  webapp/i18n/nl.json
  webapp/i18n/pl.json
  webapp/i18n/pt_BR.json
  webapp/i18n/tr.json
  webapp/i18n/uz.json
  webapp/i18n/zh_Hans.json
  webapp/src/action_types.ts
  webapp/src/actions.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/channel_call_toast.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/incoming_calls/call_incoming_condensed.tsx
  webapp/src/components/incoming_calls/expanded_call_container.tsx
  webapp/src/components/incoming_calls/hooks.ts
  webapp/src/components/switch_call_modal/component.tsx
  webapp/src/components/switch_call_modal/index.ts
  webapp/src/reducers.ts
  webapp/src/selectors.ts
  webapp/src/utils.ts
  webapp/src/websocket_handlers.ts
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#452 MM-53226 - Desktop notifications, visibility rules, ringing rules
  e2e/tests/channel_toast.spec.ts
  plugin.json
  standalone/i18n/es.json
  standalone/i18n/hr.json
  standalone/i18n/it.json
  standalone/i18n/ja.json
  standalone/i18n/ko.json
  standalone/i18n/uz.json
  standalone/i18n/zh_Hans.json
  standalone/package-lock.json
  standalone/package.json
  webapp/i18n/cs.json
  webapp/i18n/de.json
  webapp/i18n/en.json
  webapp/i18n/es.json
  webapp/i18n/fr.json
  webapp/i18n/hr.json
  webapp/i18n/it.json
  webapp/i18n/ja.json
  webapp/i18n/ko.json
  webapp/i18n/lt.json
  webapp/i18n/nl.json
  webapp/i18n/pl.json
  webapp/i18n/pt_BR.json
  webapp/i18n/tr.json
  webapp/i18n/uz.json
  webapp/i18n/zh_Hans.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/action_types.ts
  webapp/src/actions.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/channel_call_toast.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/index.ts
  webapp/src/components/incoming_calls/call_container.tsx
  webapp/src/components/incoming_calls/call_incoming.tsx
  webapp/src/components/incoming_calls/call_incoming_condensed.tsx
  webapp/src/components/incoming_calls/expanded_call_container.tsx
  webapp/src/components/incoming_calls/hooks.ts
  webapp/src/components/screen_source_modal/index.ts
  webapp/src/components/switch_call_modal/component.tsx
  webapp/src/components/switch_call_modal/index.ts
  webapp/src/index.tsx
  webapp/src/reducers.ts
  webapp/src/selectors.ts
  webapp/src/types/types.ts
  webapp/src/utils.ts
  webapp/src/webapp_globals.ts
  webapp/src/websocket_handlers.ts
Labels: 1: UX Review, 2: Dev Review

#445 MM-52857 - DM/GM ringing
  e2e/tests/channel_toast.spec.ts
  plugin.json
  server/api.go
  server/channel_state.go
  server/channel_state_test.go
  server/websocket.go
  standalone/package-lock.json
  standalone/package.json
  standalone/src/init.ts
  standalone/src/recording/index.tsx
  standalone/src/types/calls.ts
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/action_types.ts
  webapp/src/actions.ts
  webapp/src/components/call_widget/component.scss
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/index.ts
  webapp/src/components/channel_call_toast.tsx
  webapp/src/components/channel_call_toast/component.tsx
  webapp/src/components/channel_call_toast/index.js
  webapp/src/components/custom_post_types/post_type/component.tsx
  webapp/src/components/custom_post_types/post_type/index.ts
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/index.ts
  webapp/src/components/expanded_view/reaction_button.tsx
  webapp/src/components/incoming_calls/call_container.tsx
  webapp/src/components/incoming_calls/call_incoming.tsx
  webapp/src/components/incoming_calls/call_incoming_condensed.tsx
  webapp/src/components/incoming_calls/expanded_call_container.tsx
  webapp/src/components/incoming_calls/hooks.ts
  webapp/src/components/screen_source_modal/index.ts
  webapp/src/components/switch_call_modal/component.tsx
  webapp/src/components/switch_call_modal/index.ts
  webapp/src/constants.ts
  webapp/src/index.tsx
  webapp/src/reducers.ts
  webapp/src/selectors.ts
  webapp/src/types/types.ts
  webapp/src/utils.ts
  webapp/src/webapp_globals.ts
  webapp/src/websocket_handlers.ts
Labels: 3: Reviews Complete

#467 Allow compiling single build in CI
  Makefile
Labels: 3: Reviews Complete

#475 Translations update from Mattermost Weblate
  webapp/i18n/ja.json
  webapp/i18n/nl.json
  webapp/i18n/ru.json
  webapp/i18n/zh_Hans.json
  webapp/i18n/zh_Hant.json
Labels: 3: Reviews Complete

#476 Translations update from Mattermost Weblate
  standalone/i18n/ru.json
  standalone/i18n/zh_Hant.json
Labels: 3: Reviews Complete

#469 MM-53320 - Tooltip for the incoming condensed notification message
  webapp/i18n/en.json
  webapp/src/components/incoming_calls/call_incoming_condensed.tsx
Labels: 2: QA Review

#472 MM-53512 - Fix first load problems
  webapp/src/index.tsx
Labels: 3: Reviews Complete

#473 MM-53260 - Clicking notification redirects to channel
  webapp/src/components/buttons/index.tsx
  webapp/src/components/channel_call_toast.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/index.ts
  webapp/src/components/incoming_calls/call_incoming.tsx
  webapp/src/components/incoming_calls/call_incoming_condensed.tsx
  webapp/src/components/incoming_calls/hooks.ts
  webapp/src/selectors.ts
  webapp/src/utils.ts
Labels: 1: UX Review, 2: QA Review

#474 MM-53292 - Telemetry for DM/GM ringing notifications
  webapp/src/actions.ts
  webapp/src/components/incoming_calls/call_incoming_condensed.tsx
  webapp/src/components/incoming_calls/hooks.ts
  webapp/src/types/telemetry.ts
Labels: 3: Reviews Complete

#479 [MM-53804] Add simple re-try logic to job creation
  server/activate.go
  server/job_service.go
Labels: 3: Reviews Complete
