Repository mattermost/mattermost-plugin-calls, pull requests merged in 2023-06, with the labels that each got.

#442 Bump minimum supported server version to current ESR
  plugin.json
Labels: 3: Reviews Complete

#446 [MM-53069] Update calls-common
  standalone/package-lock.json
  standalone/package.json
  webapp/package-lock.json
  webapp/package.json
Labels: 3: Reviews Complete

#448 Replace Boards e2e test with Playbooks
  e2e/tests/start_call.spec.ts
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-participants-list-boards-chromium-darwin.png
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-participants-list-boards-chromium-linux.png
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-participants-list-boards-webkit-linux.png
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-participants-list-playbooks-chromium-linux.png
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-participants-list-playbooks-webkit-linux.png
Labels: 3: Reviews Complete

#450 Bump recorder version
  go.mod
  go.sum
  plugin.json
Labels: 3: Reviews Complete

#423 [MM-52485] Implement minimum version check for job service
  plugin.json
  server/job_service.go
Labels: 3: Reviews Complete

#449 MM-53274 - Add a Beta system console setting for Calls ringing
  plugin.json
  server/configuration.go
Labels: 3: Reviews Complete, Docs Needed

#457 Translations update from Mattermost Weblate
  webapp/i18n/cs.json
  webapp/i18n/de.json
  webapp/i18n/es.json
  webapp/i18n/fr.json
  webapp/i18n/hr.json
  webapp/i18n/it.json
  webapp/i18n/ja.json
  webapp/i18n/ko.json
  webapp/i18n/lt.json
  webapp/i18n/nl.json
  webapp/i18n/pl.json
  webapp/i18n/pt_BR.json
  webapp/i18n/tr.json
  webapp/i18n/uz.json
  webapp/i18n/zh_Hans.json
Labels: 2: Dev Review

#456 Translations update from Mattermost Weblate
  standalone/i18n/es.json
  standalone/i18n/hr.json
  standalone/i18n/it.json
  standalone/i18n/ja.json
  standalone/i18n/ko.json
  standalone/i18n/uz.json
  standalone/i18n/zh_Hans.json
Labels: 3: Reviews Complete

#459 Prevent config errors for new settings on update
  server/configuration.go
Labels: 3: Reviews Complete
