Repository mattermost/mattermost-plugin-calls, pull requests merged in 2023-05, with the labels that each got.

#417 Translations update from Mattermost Weblate
  webapp/i18n/cs.json
  webapp/i18n/de.json
  webapp/i18n/es.json
  webapp/i18n/fr.json
  webapp/i18n/ja.json
  webapp/i18n/lt.json
  webapp/i18n/nl.json
  webapp/i18n/pl.json
  webapp/i18n/pt_BR.json
  webapp/i18n/tr.json
  webapp/i18n/zh_Hans.json
Labels: 3: Reviews Complete

#416 Translations update from Mattermost Weblate
  standalone/i18n/cs.json
  standalone/i18n/de.json
  standalone/i18n/es.json
  standalone/i18n/fr.json
  standalone/i18n/ja.json
  standalone/i18n/lt.json
  standalone/i18n/nl.json
  standalone/i18n/pl.json
  standalone/i18n/pt_BR.json
  standalone/i18n/tr.json
  standalone/i18n/zh_Hans.json
Labels: 3: Reviews Complete

#418 [MM-48095] Mitigate potential inconsistencies with local client state
  e2e/tests/shortcuts.spec.ts
  e2e/tests/types.ts
  webapp/src/client.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/join_notification.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/index.tsx
  webapp/src/websocket.ts
Labels: 3: Reviews Complete

#415 MM-52340 - Update colour utils
  standalone/package-lock.json
  standalone/package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/utils.test.ts
  webapp/src/utils.ts
Labels: 3: Reviews Complete

#420 Use sidebar bg to generate calls bg
  standalone/src/recording/index.tsx
  webapp/src/components/expanded_view/component.tsx
Labels: 3: Reviews Complete

#419 [MM-52604] Refactor e2e users state generation
  e2e/constants.ts
  e2e/global-setup.ts
  e2e/global-teardown.ts
  e2e/package-lock.json
  e2e/package.json
  e2e/tests/global_widget.spec.ts
  e2e/tests/join_call.spec.ts
  e2e/tests/media.spec.ts
  e2e/tests/popout.spec.ts
  e2e/tests/recordings.spec.ts
  e2e/tests/shortcuts.spec.ts
  e2e/tests/start_call.spec.ts
  e2e/tests/switch_call.spec.ts
  e2e/tests/types.ts
  e2e/types.ts
  e2e/utils.ts
Labels: 3: Reviews Complete

#412 Tweak global widget sizing and positioning
  standalone/src/widget/index.tsx
  webapp/src/components/call_widget/component.tsx
Labels: 3: Reviews Complete

#426 Enable simulcast support on desktop
  standalone/src/init.ts
Labels: 3: Reviews Complete

#424 Translations update from Mattermost Weblate
  webapp/i18n/fr.json
  webapp/i18n/tr.json
Labels: 2: Dev Review

#425 Translations update from Mattermost Weblate
  standalone/i18n/fr.json
Labels: 2: Dev Review

#421 [MM-52648] Fix inconsistent participant name display in channel toast
  webapp/src/components/connected_profiles.tsx
Labels: 1: UX Review

#413 MM-48534 - Fix: Call post component honouring user's time format
  standalone/package-lock.json
  standalone/package.json
  standalone/src/recording/components/recording_view/index.tsx
  standalone/src/recording/components/recording_view/timestamp.tsx
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/call_widget/call_duration.tsx
  webapp/src/components/channel_call_toast/component.tsx
  webapp/src/components/custom_post_types/post_type/component.tsx
  webapp/src/components/custom_post_types/post_type/index.ts
  webapp/src/components/timestamp.tsx
  webapp/src/utils.test.ts
  webapp/src/utils.ts
Labels: 3: Reviews Complete

#428 Bump recorder version
  plugin.json
Labels: 3: Reviews Complete

#436 [MM-52928] Fix raising hand button state in expanded view
  e2e/tests/popout.spec.ts
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/reaction_button.tsx
Labels: 3: Reviews Complete

#283 [MM-47006] Implement basic call quality degradation logic
  webapp/i18n/en.json
  webapp/package.json
  webapp/src/client.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/widget_banner.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/global_banner.tsx
  webapp/src/constants.ts
  webapp/src/types/types.ts
Labels: 3: Reviews Complete

#430 MM-527187 - Render rtcd-related settings conditionally
  .editorconfig
  plugin.json
  webapp/i18n/en.json
  webapp/src/action_types.ts
  webapp/src/actions.ts
  webapp/src/components/admin_console_settings/hooks.tsx
  webapp/src/components/admin_console_settings/ice_host_override.tsx
  webapp/src/components/admin_console_settings/rtcd_service_url/index.tsx
  webapp/src/components/admin_console_settings/server_side_turn.tsx
  webapp/src/components/admin_console_settings/udp_server_address.tsx
  webapp/src/components/admin_console_settings/udp_server_port.tsx
  webapp/src/index.tsx
  webapp/src/reducers.ts
  webapp/src/selectors.ts
Labels: 3: Reviews Complete

#439 [MM-52977] Fix potential typeerror if config section is missing
  webapp/src/components/admin_console_settings/rtcd_service_url/index.tsx
Labels: 3: Reviews Complete
