Repository mattermost/mattermost-plugin-calls, pull requests merged in 2024-10, with the labels that each got.

#866 [MM-60187] Update Golang to v1.22
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  .golangci.yml
  README.md
  go.mod
  go.sum
  lt/go.mod
  lt/go.sum
  server/db/helper_test.go
  server/db/utils_test.go
  server/helper_test.go
  server/public/go.mod
  server/slash_command.go
Labels: 3: Reviews Complete

#875 [MM-60773] Prevent flickering when hovering on participants list if host
  e2e/tests/host_controls.spec.ts-snapshots/host-change-menu-popout-rhs-chromium-linux.png
  e2e/tests/host_controls.spec.ts-snapshots/host-change-menu-popout-rhs-webkit-linux.png
  e2e/tests/host_controls.spec.ts-snapshots/lower-hand-popout-rhs-chromium-linux.png
  e2e/tests/host_controls.spec.ts-snapshots/lower-hand-popout-rhs-webkit-linux.png
  e2e/tests/host_controls.spec.ts-snapshots/mute-menu-popout-rhs-chromium-linux.png
  e2e/tests/host_controls.spec.ts-snapshots/mute-menu-popout-rhs-webkit-linux.png
  e2e/tests/host_controls.spec.ts-snapshots/remove-popout-rhs-chromium-linux.png
  e2e/tests/host_controls.spec.ts-snapshots/remove-popout-rhs-webkit-linux.png
  e2e/tests/host_controls.spec.ts-snapshots/stop-screenshare-popout-rhs-chromium-linux.png
  e2e/tests/host_controls.spec.ts-snapshots/stop-screenshare-popout-rhs-webkit-linux.png
  webapp/src/components/expanded_view/call_participant_rhs.tsx
Labels: 3: Reviews Complete

#871 [MM-60678] Add confirmation modal when ending call for everyone
  e2e/page.ts
  e2e/tests/join_call.spec.ts
  e2e/tests/recordings.spec.ts
  webapp/i18n/en.json
  webapp/src/action_types.ts
  webapp/src/actions.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/end_call_confirmation.tsx
  webapp/src/components/custom_post_types/post_type/component.tsx
  webapp/src/components/end_call_modal/component.scss
  webapp/src/components/end_call_modal/component.tsx
  webapp/src/components/end_call_modal/index.ts
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/leave_call_menu.tsx
  webapp/src/index.tsx
  webapp/src/reducers.ts
  webapp/src/slash_commands.tsx
  webapp/src/types/types.ts
  webapp/src/utils.ts
Labels: 3: Reviews Complete

#874 [MM-60561] RTC client metrics
  go.mod
  go.sum
  lt/client/client.go
  lt/go.mod
  lt/go.sum
  server/mocks/github.com/mattermost/rtcd/service/rtc/mock_Metrics.go
  standalone/package-lock.json
  standalone/package.json
  webapp/package-lock.json
  webapp/package.json
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#870 DC messages
  go.mod
  go.sum
  lt/client/client.go
  lt/go.mod
  lt/go.sum
  server/mocks/github.com/mattermost/rtcd/service/rtc/mock_Metrics.go
  standalone/package-lock.json
  standalone/package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/client.ts
  webapp/src/setup_jest.ts
Labels: 3: Reviews Complete

#865 [MM-45894] Allow signaling through data channel
  e2e/tests/admin_console.spec.ts-snapshots/calls-system-console-general-settings-section-chromium-linux.png
  e2e/tests/admin_console.spec.ts-snapshots/calls-system-console-general-settings-section-webkit-linux.png
  go.mod
  go.sum
  lt/client/client.go
  lt/go.mod
  lt/go.sum
  plugin.json
  server/configuration.go
  server/mocks/github.com/mattermost/rtcd/service/rtc/mock_Metrics.go
  server/websocket.go
  standalone/package-lock.json
  standalone/package.json
  standalone/src/init.ts
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/client.ts
  webapp/src/components/admin_console_settings/enable_dc_signaling.tsx
  webapp/src/index.tsx
  webapp/src/setup_jest.ts
  webapp/src/types/types.ts
Labels: 3: Reviews Complete, Docs Needed

#876 Prepare v1.2.0 release
  .github/workflows/e2e.yml
  go.mod
  go.sum
  lt/go.mod
  lt/go.sum
  plugin.json
  standalone/package-lock.json
  standalone/package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/client.ts
Labels: 3: Reviews Complete

#888 [MM-61298] Fix e2e pipeline
  .github/workflows/e2e.yml
  e2e/docker/docker-compose.yaml
  e2e/docker/postgres.conf
  e2e/scripts/prepare-server.sh
Labels: 3: Reviews Complete

#886 [MM-61228] Surface transcriptions in call post
  webapp/i18n/en.json
  webapp/src/components/custom_post_types/post_type/component.tsx
  webapp/src/utils.test.ts
  webapp/src/utils.ts
Labels: 3: Reviews Complete

#881 Fix docker login step
  .github/workflows/e2e.yml
Labels: 3: Reviews Complete

#885 [MM-61166] Ensure full validation of Calls post props
  webapp/i18n/en.json
  webapp/src/components/custom_post_types/post_type/component.tsx
  webapp/src/utils.test.ts
  webapp/src/utils.ts
Labels: 3: Reviews Complete

#887 [MM-61233] Verify no error is shown when running slash commands
  e2e/tests/start_call.spec.ts
Labels: 3: Reviews Complete

#889 [MM-61166] Cherrypick to `release-0.29`
  .github/workflows/e2e.yml
  e2e/docker/docker-compose.yaml
  e2e/docker/postgres.conf
  e2e/scripts/prepare-server.sh
  e2e/scripts/run.sh
  webapp/i18n/en.json
  webapp/src/components/custom_post_types/post_type/component.tsx
  webapp/src/utils.test.ts
  webapp/src/utils.ts
Labels: 3: Reviews Complete

#890 [MM-61166] Cherrypick to `release-1.2`
  .github/workflows/e2e.yml
  e2e/docker/docker-compose.yaml
  e2e/docker/postgres.conf
  e2e/scripts/prepare-server.sh
  webapp/i18n/en.json
  webapp/src/components/custom_post_types/post_type/component.tsx
  webapp/src/utils.test.ts
  webapp/src/utils.ts
Labels: 2: Dev Review

#892 Fix E2E tests for forks
  .github/workflows/e2e.yml
Labels: 3: Reviews Complete

#894 [MM-61358] Fix flaky test job
  go.mod
  go.sum
  server/db/calls_channels_store_test.go
  server/db/calls_jobs_store_test.go
  server/db/calls_sessions_store_test.go
  server/db/calls_store_test.go
  server/db/migrate_test.go
  server/db/stats_store_test.go
  server/db/store_test.go
Labels: 3: Reviews Complete

#893 [MM-61224] Add tooltip to screen source names
  e2e/tests/desktop.spec.ts
  webapp/src/components/screen_source_modal/component.tsx
Labels: 3: Reviews Complete

#895 Update calls-common
  standalone/package-lock.json
  standalone/package.json
  webapp/package-lock.json
  webapp/package.json
Labels: 3: Reviews Complete
