Repository mattermost/mattermost-plugin-calls, pull requests merged in 2024-04, with the labels that each got.

#671 [MM-57529] e2e tests for host change slash command
  e2e/page.ts
  e2e/tests/host_controls.spec.ts
  webapp/src/components/badge.tsx
  webapp/src/components/call_widget/component.tsx
Labels: 3: Reviews Complete

#672 Bump images
  plugin.json
Labels: 3: Reviews Complete

#673 [MM-57264] Close emoji picker and bar when a reaction is chosen
  e2e/tests/popout.spec.ts
  webapp/src/components/expanded_view/reaction_button.tsx
Labels: 3: Reviews Complete

#674 SQL store: add `idx_calls_end_at`
  server/db/calls_sessions_store.go
  server/db/calls_sessions_store_test.go
  server/db/migrations/mysql/000002_create_calls.down.sql
  server/db/migrations/mysql/000002_create_calls.up.sql
  server/db/migrations/postgres/000002_create_calls.down.sql
  server/db/migrations/postgres/000002_create_calls.up.sql
Labels: 3: Reviews Complete

#677 [MM-57290] Calls widget: improve screen sharing preview UX
  webapp/src/components/call_widget/component.scss
  webapp/src/components/call_widget/component.tsx
Labels: 3: Reviews Complete

#675 [MM-57266] UX improvements to call card (post component)
  e2e/tests/join_call.spec.ts
  e2e/tests/join_call.spec.ts-snapshots/call-thread-join-chromium-linux.png
  e2e/tests/join_call.spec.ts-snapshots/call-thread-join-webkit-linux.png
  e2e/tests/join_call.spec.ts-snapshots/call-thread-leave-chromium-linux.png
  e2e/tests/join_call.spec.ts-snapshots/call-thread-leave-webkit-linux.png
  e2e/tests/start_call.spec.ts
  webapp/i18n/en.json
  webapp/src/components/avatar/avatar.tsx
  webapp/src/components/channel_call_toast.tsx
  webapp/src/components/channel_link_label/component.tsx
  webapp/src/components/custom_post_types/post_type/component.tsx
  webapp/src/components/icons/active_call_icon.tsx
  webapp/src/components/icons/leave_call_icon.tsx
Labels: 3: Reviews Complete

#685 [MM-57777] Bump calls-common dep
  standalone/package-lock.json
  standalone/package.json
  webapp/package-lock.json
  webapp/package.json
Labels: 3: Reviews Complete

#686 Fix invalid manifest type
  plugin.json
Labels: 3: Reviews Complete

#614 Make our load-test client speak :speaking_head: :magic_wand:
  .github/workflows/ci.yml
  Makefile
  go.mod
  lt/README.md
  lt/client/client.go
  lt/client/tts.go
  lt/cmd/lt/main.go
  lt/cmd/speech/main.go
  lt/go.mod
  lt/go.sum
  lt/samples/speech_0.ogg
  lt/samples/speech_0.txt
  lt/samples/speech_1.ogg
  lt/samples/speech_1.txt
Labels: 3: Reviews Complete

#632 Script-driven tts loadtesting, using Polly
  lt/client/client.go
  lt/client/tts.go
  lt/cmd/speech/main.go
  lt/cmd/speech/script-no-crosstalk.txt
  lt/cmd/speech/script.go
  lt/cmd/speech/script.txt
  lt/cmd/speech/script_test.go
  lt/go.mod
  lt/go.sum
Labels: 3: Reviews Complete

#689 [MM-57799] Add manifest check step to Makefile
  Makefile
  build/go.mod
  build/go.sum
  build/manifest/main.go
  build/pluginctl/main.go
Labels: 3: Reviews Complete

#679 Migrate to styled components v6
  e2e/tests/join_call.spec.ts
  e2e/tests/join_call.spec.ts-snapshots/call-thread-join-chromium-linux.png
  e2e/tests/join_call.spec.ts-snapshots/call-thread-join-webkit-linux.png
  e2e/tests/join_call.spec.ts-snapshots/call-thread-leave-chromium-linux.png
  e2e/tests/join_call.spec.ts-snapshots/call-thread-leave-webkit-linux.png
  e2e/tests/start_call.spec.ts
  standalone/package-lock.json
  standalone/package.json
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/cloud_pricing/modals.tsx
  webapp/src/components/admin_console_settings/recordings/enable_recordings.tsx
  webapp/src/components/admin_console_settings/recordings/modals.tsx
  webapp/src/components/admin_console_settings/rtcd_service_url/index.tsx
  webapp/src/components/admin_console_settings/rtcd_service_url/modals.tsx
  webapp/src/components/avatar/avatar.tsx
  webapp/src/components/badge.tsx
  webapp/src/components/call_widget/loading_overlay.tsx
  webapp/src/components/call_widget/unavailable_icon_wrapper.tsx
  webapp/src/components/call_widget/widget_banner.tsx
  webapp/src/components/call_widget/widget_button.tsx
  webapp/src/components/channel_call_toast.tsx
  webapp/src/components/channel_header_button/component.tsx
  webapp/src/components/channel_header_dropdown_button/component.tsx
  webapp/src/components/channel_link_label/component.tsx
  webapp/src/components/custom_post_types/post_type/component.tsx
  webapp/src/components/custom_post_types/post_type_transcription.tsx
  webapp/src/components/expanded_view/controls_button.tsx
  webapp/src/components/expanded_view/global_banner.tsx
  webapp/src/components/expanded_view/in_call_prompt.tsx
  webapp/src/components/expanded_view/reaction_button.tsx
  webapp/src/components/icons/active_call_icon.tsx
  webapp/src/components/icons/leave_call_icon.tsx
  webapp/src/components/incoming_calls/call_container.tsx
  webapp/src/components/modals/index.tsx
  webapp/src/components/reaction_stream/reaction_stream.tsx
  webapp/src/components/shared.tsx
  webapp/src/types/external/styled-components.d.ts
Labels: 3: Reviews Complete

#681 [MM-57737] Improve client side call state consistency
  server/client_message.go
  server/websocket.go
  server/websocket_test.go
  webapp/src/components/expanded_view/component.tsx
  webapp/src/index.tsx
  webapp/src/utils.ts
Labels: 3: Reviews Complete

#693 [MM-57571] Improve linting
  .github/workflows/ci.yml
  .golangci.yml
  go.mod
  lt/client/client.go
  lt/client/tts.go
  lt/cmd/speech/main.go
  lt/cmd/speech/script.go
  server/bot_api.go
  server/cloud_limits.go
  server/db/migrate.go
  server/host_controls.go
  server/log.go
  server/main.go
  server/plugin_test.go
  server/public/job.go
  server/push_notifications.go
  server/rtcd.go
  server/state_test.go
  server/testutils/containers.go
  server/utils.go
  server/websocket.go
Labels: 3: Reviews Complete

#690 Loadtest: Move scripts to a scripts directory
  lt/cmd/speech/main.go
  lt/scripts/script-no-crosstalk.txt
  lt/scripts/script.txt
Labels: 3: Reviews Complete

#695 Fix fetching call state in popout
  webapp/src/components/expanded_view/component.tsx
Labels: 3: Reviews Complete

#694 Make update and delete store operations idempotent
  server/db/calls_channels_store.go
  server/db/calls_channels_store_test.go
  server/db/calls_jobs_store.go
  server/db/calls_jobs_store_test.go
  server/db/calls_sessions_store.go
  server/db/calls_sessions_store_test.go
  server/db/calls_store.go
  server/db/calls_store_test.go
Labels: 3: Reviews Complete

#684 [MM-57250] Add spinner animation to start/join call button
  standalone/src/init.ts
  webapp/i18n/en.json
  webapp/src/action_types.ts
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/call_error_modal.tsx
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/index.ts
  webapp/src/components/call_widget/loading_overlay.tsx
  webapp/src/components/channel_header_button.tsx
  webapp/src/components/channel_header_button/index.ts
  webapp/src/components/shared.tsx
  webapp/src/index.tsx
  webapp/src/reducers.ts
  webapp/src/selectors.ts
  webapp/src/utils.ts
Labels: 3: Reviews Complete

#697 [MM-57843] Use official client for load-testing
  lt/client/client.go
  lt/cmd/lt/main.go
  lt/cmd/speech/main.go
  lt/go.mod
  lt/go.sum
  lt/ws/client.go
  lt/ws/client_test.go
Labels: 3: Reviews Complete

#678 [MM-57471] Host controls: Three dot menus
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-participants-list-playbooks-chromium-linux.png
  e2e/tests/start_call.spec.ts-snapshots/calls-widget-participants-list-playbooks-webkit-linux.png
  server/api_router.go
  server/host_controls_api.go
  standalone/src/recording/components/recording_view/index.tsx
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/actions.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/participant.tsx
  webapp/src/components/call_widget/participants_list.tsx
  webapp/src/components/dot_menu/dot_menu.tsx
  webapp/src/components/dot_menu/dropdown.tsx
  webapp/src/components/expanded_view/call_participant.tsx
  webapp/src/components/expanded_view/call_participant_rhs.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/hooks.ts
  webapp/src/components/expanded_view/styled_components.tsx
  webapp/src/components/host_controls_menu.tsx
  webapp/src/components/icons/monitor_account.tsx
  webapp/src/components/icons/three_dots.tsx
  webapp/src/selectors.ts
Labels: 3: Reviews Complete, Do Not Merge

#698 feat: Initial commit for e2e testing migration
  .github/workflows/e2e.yml
  .gitignore
  .gitlab-ci.yml
  e2e/Playwright.Dockerfile
  e2e/overlay-config.jq
  e2e/package.json
  e2e/scripts/merge-reports.js
  e2e/scripts/prepare-server.sh
  e2e/scripts/run.sh
Labels: 2: Dev Review

#707 [MM-57965] fix Websocket reconnect handler
  e2e/tests/popout.spec.ts
  e2e/types.ts
  webapp/src/index.tsx
Labels: 3: Reviews Complete

#710 Run e2e tests on tags and main branch
  .github/workflows/e2e.yml
Labels: 3: Reviews Complete

#700 [MM-57323] Update node/npm to match webapp
  .nvmrc
  standalone/package-lock.json
  standalone/package.json
  standalone/webpack.config.js
  webapp/install_mattermost_webapp.sh
  webapp/package-lock.json
  webapp/package.json
  webapp/src/actions.ts
  webapp/src/cloud_pricing/modals.tsx
  webapp/src/components/admin_console_settings/hooks.tsx
  webapp/src/components/call_error_modal.tsx
  webapp/src/components/dot_menu/dropdown.tsx
  webapp/src/components/end_call_modal/component.tsx
  webapp/src/webapp_globals.ts
  webapp/webpack.config.js
Labels: 3: Reviews Complete

#709 [MM-57967] Add HostControlsAllowed
  server/api.go
  server/configuration.go
  server/configuration_test.go
  standalone/package-lock.json
  standalone/package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/selectors.ts
  webapp/src/types/types.ts
Labels: 3: Reviews Complete

#712 [MM-58016] Some eslint simplifications
  standalone/.eslintrc.json
  standalone/package-lock.json
  standalone/package.json
  webapp/.eslintrc.json
  webapp/package-lock.json
  webapp/package.json
Labels: 3: Reviews Complete

#713 [MM-58006] System console live captions and transcriber settings visibility
  webapp/src/components/admin_console_settings/recordings/live_captions_language.tsx
  webapp/src/components/admin_console_settings/recordings/live_captions_model_size.tsx
  webapp/src/components/admin_console_settings/recordings/live_captions_num_threads_per_transcriber.tsx
  webapp/src/components/admin_console_settings/recordings/live_captions_num_transcribers.tsx
  webapp/src/components/admin_console_settings/recordings/transcriber_model_size.tsx
  webapp/src/components/admin_console_settings/recordings/transcriber_num_threads.tsx
Labels: 3: Reviews Complete

#705 [MM-57464] Host controls: Lower hand; host controls notifications
  server/api_router.go
  server/host_controls.go
  server/host_controls_api.go
  server/websocket.go
  standalone/src/init.ts
  standalone/src/recording/components/recording_view/index.tsx
  webapp/i18n/en.json
  webapp/src/action_types.ts
  webapp/src/actions.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/index.ts
  webapp/src/components/call_widget/participant.tsx
  webapp/src/components/expanded_view/call_participant.tsx
  webapp/src/components/expanded_view/call_participant_rhs.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/in_call_prompt.tsx
  webapp/src/components/host_controls_menu.tsx
  webapp/src/components/host_notifications.tsx
  webapp/src/components/reaction_stream/reaction_stream.tsx
  webapp/src/constants.ts
  webapp/src/index.tsx
  webapp/src/reducers.ts
  webapp/src/selectors.ts
  webapp/src/types/types.ts
  webapp/src/websocket_handlers.ts
Labels: 3: Reviews Complete
