Repository mattermost/mattermost-plugin-calls, pull requests merged in 2024-05, with the labels that each got.

#723 [MM-58125] Fix Client4 initiated requests when running under subpath
  webapp/src/index.tsx
Labels: 3: Reviews Complete

#715 [MM-57263] Tweaks to expanded view
  e2e/tests/popout.spec.ts-snapshots/expanded-view-controls-chromium-linux.png
  e2e/tests/popout.spec.ts-snapshots/expanded-view-controls-webkit-linux.png
  webapp/i18n/en.json
  webapp/src/components/badge.tsx
  webapp/src/components/expanded_view/component.scss
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/controls_button.tsx
  webapp/src/components/expanded_view/reaction_button.tsx
  webapp/src/components/incoming_calls/expanded_incoming_call_container.tsx
Labels: 3: Reviews Complete

#727 Bump rtcd to latest v0.15.0
  go.mod
  go.sum
  lt/go.mod
  lt/go.sum
  server/activate.go
Labels: 3: Reviews Complete

#714 [MM-58002] Ensure call state mutating operations are executed in the right order
  e2e/tests/join_call.spec.ts
  standalone/src/init.ts
  standalone/src/recording/index.tsx
  webapp/src/action_types.ts
  webapp/src/actions.ts
  webapp/src/index.tsx
  webapp/src/reducers.ts
  webapp/src/selectors.ts
  webapp/src/utils.ts
  webapp/src/websocket_handlers.ts
Labels: 3: Reviews Complete

#725 [MM-58033] Fix: Incoming call banner in expanded view not working
  e2e/tests/notifications.spec.ts
  webapp/src/components/incoming_calls/call_incoming_condensed.tsx
Labels: 3: Reviews Complete

#730 MM-58165 - Updating calls not allowed modal
  webapp/src/components/generic_modal.tsx
  webapp/src/components/modals/index.tsx
Labels: 2: Dev Review, 2: QA Review

#726 [MM-57470] Host controls: Mute all
  server/api_router.go
  server/host_controls.go
  server/host_controls_api.go
  webapp/i18n/en.json
  webapp/src/actions.ts
  webapp/src/components/call_widget/participants_list.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/index.ts
Labels: 3: Reviews Complete

#733 Fix live captions icon
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/icons/cc_icon.tsx
Labels: 3: Reviews Complete

#735 [MM-57919] Use new host controls ws msgs
  standalone/package-lock.json
  standalone/package.json
  standalone/src/init.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/websocket_handlers.ts
Labels: 3: Reviews Complete

#736 Fix pop out height
  webapp/src/components/expanded_view/component.tsx
Labels: 3: Reviews Complete

#737 [MM-58232] Host notices: fix background and color
  webapp/src/components/host_notices.tsx
Labels: 3: Reviews Complete

#739 chore(cypress): Fix user profile e2e test
  e2e/tests/join_call.spec.ts
Labels: 3: Reviews Complete

#738 [MM-58265] Fix outstanding CSS issues in pop out view
  webapp/src/components/expanded_view/component.tsx
Labels: 3: Reviews Complete

#743 Remove question mark from meeting summary button.
  webapp/i18n/en.json
  webapp/src/components/custom_post_types/post_type_transcription.tsx
Labels: 3: Reviews Complete

#741 [MM-58195] [MM-58283] Fix banner
  e2e/tests/start_call.spec.ts
  webapp/i18n/en.json
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/widget_banner.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/global_banner.tsx
  webapp/src/constants.ts
Labels: 3: Reviews Complete

#746 [MM-58221] Update Join and muted notices to match the new notices style
  webapp/i18n/en.json
  webapp/src/components/call_widget/component.scss
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/call_widget/join_notification.tsx
  webapp/src/components/host_notices.tsx
Labels: 3: Reviews Complete

#742 [MM-58325] Handle stuck session edge case
  server/websocket.go
Labels: 3: Reviews Complete

#719 [MM-57263] Implement call settings in popout window
  e2e/tests/popout.spec.ts-snapshots/expanded-view-controls-chromium-linux.png
  e2e/tests/popout.spec.ts-snapshots/expanded-view-controls-webkit-linux.png
  e2e/tests/recordings.spec.ts
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/call_widget/component.tsx
  webapp/src/components/expanded_view/call_settings.tsx
  webapp/src/components/expanded_view/component.tsx
  webapp/src/components/expanded_view/index.ts
Labels: 3: Reviews Complete, Docs Needed

#721 [MM-58085] Improve calls load balancing logic
  .mockery.yaml
  go.mod
  go.sum
  server/interfaces/interfaces.go
  server/mocks/github.com/mattermost/mattermost-plugin-calls/server/interfaces/mock_Metrics.go
  server/mocks/github.com/mattermost/mattermost-plugin-calls/server/interfaces/mock_RTCDClient.go
  server/mocks/github.com/mattermost/mattermost/server/public/plugin/mock_API.go
  server/rtcd.go
  server/rtcd_test.go
Labels: 3: Reviews Complete

#609 [MM-53455] Broadcast certain call events to participants only
  server/api.go
  server/bot_api.go
  server/host_controls.go
  server/job_service.go
  server/plugin.go
  server/recording_api.go
  server/rtcd.go
  server/session.go
  server/state.go
  server/transcription_api.go
  server/utils.go
  server/utils_test.go
  server/websocket.go
  server/websocket_test.go
Labels: 3: Reviews Complete

#704 [MM-54335] Batching of call join/leave operations
  .mockery.yaml
  server/api.go
  server/batching/batcher.go
  server/batching/batcher_test.go
  server/db/calls_sessions_store.go
  server/db/calls_sessions_store_test.go
  server/helper_test.go
  server/main.go
  server/mocks/github.com/mattermost/rtcd/service/rtc/mock_Metrics.go
  server/plugin.go
  server/rtcd.go
  server/session.go
  server/session_test.go
  server/state.go
  server/state_test.go
  server/sync.go
  server/websocket.go
  server/websocket_test.go
Labels: 3: Reviews Complete

#711 [MM-57954] Use direct db connection for writer
  server/activate.go
  server/db.go
  server/db/calls_channels_store.go
  server/db/calls_jobs_store.go
  server/db/calls_sessions_store.go
  server/db/calls_store.go
  server/db/helper_test.go
  server/db/migrate.go
  server/db/misc_store.go
  server/db/store.go
  server/db/store_test.go
  server/db/utils.go
  server/db/utils_test.go
  server/helper_test.go
  server/interfaces/interfaces.go
  server/mocks/github.com/mattermost/mattermost-plugin-calls/server/interfaces/mock_Metrics.go
  server/performance/metrics.go
Labels: 3: Reviews Complete

#718 Load-testing tweaks for speech; mute/unmute; benchmarking script
  Makefile
  lt/client/client.go
  lt/cmd/speech/main.go
  lt/cmd/speech/script.go
  lt/cmd/speech/script_test.go
  lt/scripts/script-for-benchmarking.txt
  server/performance/metrics.go
Labels: 3: Reviews Complete

#747 [MM-58259] [MM-58260] Move the /call end command to host controls
  e2e/page.ts
  e2e/tests/channel_toast.spec.ts
  e2e/tests/host_controls.spec.ts
  e2e/tests/notifications.spec.ts-snapshots/call-incoming-condensed-notification-gm-chromium-darwin.png
  e2e/tests/notifications.spec.ts-snapshots/call-incoming-notification-dm-chromium-darwin.png
  e2e/tests/notifications.spec.ts-snapshots/call-incoming-notification-gm-chromium-darwin.png
  e2e/tests/slash_commands.spec.ts
  server/api.go
  server/api_router.go
  server/host_controls.go
  server/host_controls_api.go
  webapp/src/action_types.ts
  webapp/src/actions.ts
  webapp/src/components/channel_call_toast.tsx
  webapp/src/components/channel_header_button.tsx
  webapp/src/components/channel_header_dropdown_button/index.ts
  webapp/src/components/channel_link_label/component.tsx
  webapp/src/components/channel_link_label/index.ts
  webapp/src/components/end_call_modal/index.ts
  webapp/src/index.tsx
  webapp/src/reducers.ts
  webapp/src/selectors.ts
  webapp/src/slash_commands.tsx
  webapp/src/websocket_handlers.ts
Labels: 3: Reviews Complete

#756 Fix leaking batchers in HA environment
  server/session.go
Labels: 3: Reviews Complete

#745 E2E test to check if call button in user profile popover is disabled after call is started
  e2e/tests/join_call.spec.ts
Labels: 3: Reviews Complete
